# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/93dda487-f780-401d-ae2b-a21503cb4184";
      fsType = "btrfs";
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/93dda487-f780-401d-ae2b-a21503cb4184";
      fsType = "btrfs";
      options = [ "subvol=@/opt" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/93dda487-f780-401d-ae2b-a21503cb4184";
      fsType = "btrfs";
      options = [ "subvol=@/srv" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/93dda487-f780-401d-ae2b-a21503cb4184";
      fsType = "btrfs";
      options = [ "subvol=@/root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/93dda487-f780-401d-ae2b-a21503cb4184";
      fsType = "btrfs";
      options = [ "subvol=@/nix" ];
    };

  fileSystems."/usr/local" =
    { device = "/dev/disk/by-uuid/93dda487-f780-401d-ae2b-a21503cb4184";
      fsType = "btrfs";
      options = [ "subvol=@/usr/local" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/76D1-23B3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9b544903-a2b1-45fe-b83c-95c99addbdcf";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/work" =
    { device = "/dev/disk/by-uuid/5b6aff7d-4a90-4e83-b134-425ff53b86cc";
      fsType = "btrfs";
      options = [ "subvol=@/work" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f9cac889-cebd-4eee-9a5c-00edc5c8e956"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
